version: '3.8'
services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"
#  liquibase:
#    container_name: liquibase
#    depends_on:
#      - postgres
#    image: liquibase
#    volumes:
#      - ./liquibase/db/changelog/:/liquibase/changelog/
#    command: update --url=jdbc:postgresql://postgres:5432/postgres --username=postgres --password=postgres --changeLogFile=master.yaml
