services:
  application:
    build: application/
    container_name: application
    depends_on:
      - database
      - liquibase
    environment:
      - HOST=database
    ports:
      - "8080:8080"
  database:
    container_name: database
    environment:
      - POSTGRES_PASSWORD=postgres
    image: postgres
    ports:
      - "5432:5432"
  liquibase:
    build: liquibase/
    container_name: liquibase
    depends_on:
      - database
    environment:
      - HOST=database
