spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${HOST}:5432/postgres
    username: postgres
    password: postgres
  jpa:
    mapping-resources:
      - orm/film-repository.xml
      - orm/user-repository.xml
    open-in-view: false
