--liquibase formatted sql

--changeset author:01-create-tables.sql

CREATE TABLE genres (
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name TEXT                                    NOT NULL,
    CONSTRAINT genres_pkey PRIMARY KEY (id)
);

CREATE TABLE mpa (
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name TEXT                                    NOT NULL,
    CONSTRAINT mpa_pkey PRIMARY KEY (id)
);

CREATE TABLE directors (
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name TEXT                                    NOT NULL,
    CONSTRAINT directors_pkey PRIMARY KEY (id)
);

CREATE TABLE films (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name         TEXT                                    NOT NULL,
    description  TEXT                                    NOT NULL,
    release_date TIMESTAMP WITH TIME ZONE                NOT NULL,
    duration     INTEGER                                 NOT NULL,
    mpa_id       BIGINT                                  NOT NULL,
    likes_amount INTEGER                                 NOT NULL,
    CONSTRAINT films_pkey PRIMARY KEY (id),
    FOREIGN KEY (mpa_id) REFERENCES mpa (id) ON DELETE RESTRICT
);

CREATE TABLE users (
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email    TEXT                                    NOT NULL,
    login    TEXT                                    NOT NULL,
    name     TEXT,
    birthday TIMESTAMP WITH TIME ZONE                NOT NULL,
    CONSTRAINT users_pkey PRIMARY KEY (id)
);

CREATE TABLE events (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created    TIMESTAMP WITH TIME ZONE                NOT NULL,
    user_id    BIGINT                                  NOT NULL,
    event_type TEXT                                    NOT NULL,
    operation  TEXT                                    NOT NULL,
    entity_id  BIGINT                                  NOT NULL,
    CONSTRAINT events_pkey PRIMARY KEY (id),
    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE reviews (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    content     TEXT                                    NOT NULL,
    is_positive BOOLEAN                                 NOT NULL,
    user_id     BIGINT                                  NOT NULL,
    film_id     BIGINT                                  NOT NULL,
    useful      INTEGER                                 NOT NULL,
    CONSTRAINT reviews_pkey PRIMARY KEY (id),
    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    FOREIGN KEY (film_id) REFERENCES films (id) ON DELETE CASCADE
);

CREATE TABLE film_genres (
    film_id  BIGINT NOT NULL,
    genre_id BIGINT NOT NULL,
    CONSTRAINT film_genres_pkey PRIMARY KEY (film_id, genre_id),
    FOREIGN KEY (film_id) REFERENCES films (id) ON DELETE CASCADE,
    FOREIGN KEY (genre_id) REFERENCES genres (id) ON DELETE CASCADE
);

CREATE TABLE film_likes (
    film_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    CONSTRAINT film_likes_pkey PRIMARY KEY (film_id, user_id),
    FOREIGN KEY (film_id) REFERENCES films (id) ON DELETE CASCADE,
    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE film_directors (
    film_id     BIGINT NOT NULL,
    director_id BIGINT NOT NULL,
    CONSTRAINT film_directors_pkey PRIMARY KEY (film_id, director_id),
    FOREIGN KEY (film_id) REFERENCES films (id) ON DELETE CASCADE,
    FOREIGN KEY (director_id) REFERENCES directors (id) ON DELETE CASCADE
);

CREATE TABLE friendship (
    requesting_user_id BIGINT NOT NULL,
    receiving_user_id  BIGINT NOT NULL,
    CONSTRAINT friendship_pkey PRIMARY KEY (requesting_user_id, receiving_user_id),
    FOREIGN KEY (requesting_user_id) REFERENCES users (id) ON DELETE CASCADE,
    FOREIGN KEY (receiving_user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE review_marks (
    review_id BIGINT NOT NULL,
    user_id   BIGINT NOT NULL,
    mark_type TEXT   NOT NULL,
    CONSTRAINT review_marks_pkey PRIMARY KEY (review_id, user_id),
    FOREIGN KEY (review_id) REFERENCES reviews (id) ON DELETE CASCADE,
    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

--rollback DROP TABLE review_marks;
--rollback DROP TABLE friendship;
--rollback DROP TABLE film_directors;
--rollback DROP TABLE film_likes;
--rollback DROP TABLE film_genres;
--rollback DROP TABLE reviews;
--rollback DROP TABLE events;
--rollback DROP TABLE users;
--rollback DROP TABLE films;
--rollback DROP TABLE directors;
--rollback DROP TABLE mpa;
--rollback DROP TABLE genres;
