--liquibase formatted sql

--changeset author:01-create-tables.sql

CREATE TABLE users (
    id       bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email    text                                    NOT NULL,
    login    text                                    NOT NULL,
    name     text,
    birthday timestamp with time zone                NOT NULL,
    CONSTRAINT users_pkey PRIMARY KEY (id)
);

CREATE TABLE friendship (
    requesting_user_id bigint NOT NULL,
    receiving_user_id  bigint NOT NULL,
    CONSTRAINT friendship_pkey PRIMARY KEY (requesting_user_id, receiving_user_id),
    FOREIGN KEY (requesting_user_id) REFERENCES users (id) ON DELETE CASCADE,
    FOREIGN KEY (receiving_user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE mpa (
    id   bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name text                                    NOT NULL,
    CONSTRAINT mpa_pkey PRIMARY KEY (id)
);

CREATE TABLE genre (
    id   bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name text                                    NOT NULL,
    CONSTRAINT genre_pkey PRIMARY KEY (id)
);

CREATE TABLE director (
    id   bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name text                                    NOT NULL,
    CONSTRAINT director_pkey PRIMARY KEY (id)
);

CREATE TABLE film (
    id           bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name         text                                    NOT NULL,
    description  text                                    NOT NULL,
    release_date timestamp with time zone                NOT NULL,
    duration     integer                                 NOT NULL,
    mpa_id       bigint                                  NOT NULL,
    likes_amount integer                                 NOT NULL,
    CONSTRAINT film_pkey PRIMARY KEY (id),
    FOREIGN KEY (mpa_id) REFERENCES mpa (id) ON DELETE RESTRICT
);

CREATE TABLE film_genre (
    film_id  bigint NOT NULL,
    genre_id bigint NOT NULL,
    CONSTRAINT film_genre_pkey PRIMARY KEY (film_id, genre_id),
    FOREIGN KEY (film_id) REFERENCES film (id) ON DELETE CASCADE,
    FOREIGN KEY (genre_id) REFERENCES genre (id) ON DELETE CASCADE
);

CREATE TABLE film_director (
    film_id     bigint NOT NULL,
    director_id bigint NOT NULL,
    CONSTRAINT film_director_pkey PRIMARY KEY (film_id, director_id),
    FOREIGN KEY (film_id) REFERENCES film (id) ON DELETE CASCADE,
    FOREIGN KEY (director_id) REFERENCES director (id) ON DELETE CASCADE
);

CREATE TABLE film_like (
    film_id bigint NOT NULL,
    user_id bigint NOT NULL,
    CONSTRAINT film_like_pkey PRIMARY KEY (film_id, user_id),
    FOREIGN KEY (film_id) REFERENCES film (id) ON DELETE CASCADE,
    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE event (
    id         bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created    timestamp with time zone                NOT NULL,
    user_id    bigint                                  NOT NULL,
    event_type text                                    NOT NULL,
    operation  text                                    NOT NULL,
    entity_id  bigint                                  NOT NULL,
    CONSTRAINT event_pkey PRIMARY KEY (id),
    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE review (
    id          bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    content     text                                    NOT NULL,
    is_positive BOOLEAN                                 NOT NULL,
    user_id     bigint                                  NOT NULL,
    film_id     bigint                                  NOT NULL,
    useful      integer                                 NOT NULL,
    CONSTRAINT review_pkey PRIMARY KEY (id),
    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    FOREIGN KEY (film_id) REFERENCES film (id) ON DELETE CASCADE
);

CREATE TABLE review_mark (
    review_id bigint NOT NULL,
    user_id   bigint NOT NULL,
    mark_type text   NOT NULL,
    CONSTRAINT review_mark_pkey PRIMARY KEY (review_id, user_id),
    FOREIGN KEY (review_id) REFERENCES review (id) ON DELETE CASCADE,
    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

--rollback DROP TABLE review_mark;
--rollback DROP TABLE review;
--rollback DROP TABLE event;
--rollback DROP TABLE film_like;
--rollback DROP TABLE film_director;
--rollback DROP TABLE film_genre;
--rollback DROP TABLE film;
--rollback DROP TABLE director;
--rollback DROP TABLE genre;
--rollback DROP TABLE mpa;
--rollback DROP TABLE friendship;
--rollback DROP TABLE users;
