spring:
  application:
    name: backend
  datasource:
    driver-class-name: org.postgresql.Driver
    url: "jdbc:postgresql://localhost:5432/postgres"
    username: postgres
    password: postgres
  jpa:
    open-in-view: false
#logging:
#  level:
#    org:
#      springframework:
#        jdbc:
#          core: debug
